<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFWTD1KU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFWTD1KU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFWTD1KU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFWTD1KU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFWTD1KU\App_KernelDevDebugContainer([
    'container.build_hash' => 'FWTD1KU',
    'container.build_id' => '376f04ef',
    'container.build_time' => 1638352983,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFWTD1KU');
